#ifndef XYGRAPH_GLOBAL_HPP
#define XYGRAPH_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(XYGRAPH_LIBRARY)
#  define XYGRAPHSHARED_EXPORT Q_DECL_EXPORT
#else
#  define XYGRAPHSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // XYGRAPH_GLOBAL_HPP
